server:
  port: 8084

spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: duydat
    password: dat123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


